package datos;
// Generated 27-may-2015 0:01:58 by Hibernate Tools 4.3.1



/**
 * Actividades generated by hbm2java
 */
public class Actividades  implements java.io.Serializable {


     private Integer idActividad;
     private String nombreActividad;
     private Integer empleadoEncargadoActividad;
     private Integer cuotaPrecio;
     private Integer idtarifasActividadestarifas;

    public Actividades() {
    }

    public Actividades(String nombreActividad, Integer empleadoEncargadoActividad, Integer cuotaPrecio, Integer idtarifasActividadestarifas) {
       this.nombreActividad = nombreActividad;
       this.empleadoEncargadoActividad = empleadoEncargadoActividad;
       this.cuotaPrecio = cuotaPrecio;
       this.idtarifasActividadestarifas = idtarifasActividadestarifas;
    }
   
    public Integer getIdActividad() {
        return this.idActividad;
    }
    
    public void setIdActividad(Integer idActividad) {
        this.idActividad = idActividad;
    }
    public String getNombreActividad() {
        return this.nombreActividad;
    }
    
    public void setNombreActividad(String nombreActividad) {
        this.nombreActividad = nombreActividad;
    }
    public Integer getEmpleadoEncargadoActividad() {
        return this.empleadoEncargadoActividad;
    }
    
    public void setEmpleadoEncargadoActividad(Integer empleadoEncargadoActividad) {
        this.empleadoEncargadoActividad = empleadoEncargadoActividad;
    }
    public Integer getCuotaPrecio() {
        return this.cuotaPrecio;
    }
    
    public void setCuotaPrecio(Integer cuotaPrecio) {
        this.cuotaPrecio = cuotaPrecio;
    }
    public Integer getIdtarifasActividadestarifas() {
        return this.idtarifasActividadestarifas;
    }
    
    public void setIdtarifasActividadestarifas(Integer idtarifasActividadestarifas) {
        this.idtarifasActividadestarifas = idtarifasActividadestarifas;
    }




}


