package datos;
// Generated 10-may-2015 17:08:22 by Hibernate Tools 4.3.1



/**
 * Actividadestarifas generated by hbm2java
 */
public class Actividadestarifas  implements java.io.Serializable {


     private ActividadestarifasId id;

    public Actividadestarifas() {
    }

    public Actividadestarifas(ActividadestarifasId id) {
       this.id = id;
    }
   
    public ActividadestarifasId getId() {
        return this.id;
    }
    
    public void setId(ActividadestarifasId id) {
        this.id = id;
    }




}


