package datos;
// Generated 25-may-2015 23:18:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HorariosActividades generated by hbm2java
 */
public class HorariosActividades  implements java.io.Serializable {


     private Integer idHorario;
     private Integer idactividadHorario;
     private String diaHorario;
     private Date horainicioHorario;
     private Date horafinHorario;

    public HorariosActividades() {
    }

    public HorariosActividades(Integer idactividadHorario, String diaHorario, Date horainicioHorario, Date horafinHorario) {
       this.idactividadHorario = idactividadHorario;
       this.diaHorario = diaHorario;
       this.horainicioHorario = horainicioHorario;
       this.horafinHorario = horafinHorario;
    }
   
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }
    public Integer getIdactividadHorario() {
        return this.idactividadHorario;
    }
    
    public void setIdactividadHorario(Integer idactividadHorario) {
        this.idactividadHorario = idactividadHorario;
    }
    public String getDiaHorario() {
        return this.diaHorario;
    }
    
    public void setDiaHorario(String diaHorario) {
        this.diaHorario = diaHorario;
    }
    public Date getHorainicioHorario() {
        return this.horainicioHorario;
    }
    
    public void setHorainicioHorario(Date horainicioHorario) {
        this.horainicioHorario = horainicioHorario;
    }
    public Date getHorafinHorario() {
        return this.horafinHorario;
    }
    
    public void setHorafinHorario(Date horafinHorario) {
        this.horafinHorario = horafinHorario;
    }




}


