/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gimnasio.ventanas;

import tablas.ModeloTablaClientes;
import datos.Clientes;
import datos.Tarifas;
import gimnasio.gestoras.Gestora;
import javax.swing.JOptionPane;
import gimnasio.gestoras.GestoraClientes;
import gimnasio.gestoras.GestoraTarifas;
import gimnasio.gestoras.Login;
import gimnasio.gestoras.Patrones;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author Eva María de Vena
 */
public class VentanaClientes extends javax.swing.JDialog {

    GestoraClientes gestora = new GestoraClientes();
    VentanaLogin v = new VentanaLogin();

    /**
     * Creates new form Clientes
     */
    public VentanaClientes(Frame owner, boolean modal) {
        super(owner, modal);
        initComponents();
        tablaClientes.setAutoCreateRowSorter(true);
        tableBusquedas.setAutoCreateRowSorter(true);
        setLocationRelativeTo(null);
        VentanaUtils.limpiarFormulario(jPanel1);
        getTarifas();
        tablaClientes.setModel(new ModeloTablaClientes(GestoraClientes.recuperarClientes()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFormaDePago = new javax.swing.ButtonGroup();
        Ventana_clientes_busqueda = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txNuevoNombre = new javax.swing.JTextField();
        txNuevoApellidos = new javax.swing.JTextField();
        txNuevoDni = new javax.swing.JTextField();
        txNuevoTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txNumeroDomicilio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txNuevoPiso = new javax.swing.JTextField();
        txNuevoDireccion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txNuevoMovil = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        rbEfectivo = new javax.swing.JRadioButton();
        rbCuentaBancaria = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        txNuevoNacimiento = new com.toedter.calendar.JDateChooser();
        txNuevoEmail = new javax.swing.JTextField();
        cbNuevoTarifa = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txNuevoCuentaBancaria = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txNuevoCodigoPostal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txNuevoLocalidad = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txNuevoProvincia = new javax.swing.JTextField();
        botonLimpiar = new javax.swing.JButton();
        bGuardarCliente = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        botonEditarCliente = new javax.swing.JButton();
        botonBorrarCliente = new javax.swing.JButton();
        botonDetalles = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txBusqueda = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBusquedas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellidos:");

        jLabel3.setText("Número de telefono:");

        jLabel4.setText("DNI:");

        txNuevoNombre.setText("jTextField1");

        txNuevoApellidos.setText("jTextField2");

        txNuevoDni.setText("jTextField3");

        txNuevoTelefono.setText("jTextField4");
        txNuevoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNuevoTelefonoActionPerformed(evt);
            }
        });
        txNuevoTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txNuevoTelefonoKeyTyped(evt);
            }
        });

        jLabel5.setText("Dirección:");

        jLabel6.setText("Número:");

        txNumeroDomicilio.setText("jTextField6");

        jLabel7.setText("Piso:");

        txNuevoPiso.setText("jTextField7");

        txNuevoDireccion.setText("jTextField9");

        jLabel13.setText("Numero de movil:");

        txNuevoMovil.setText("jTextField1");

        jLabel10.setText("Forma de pago:");

        bgFormaDePago.add(rbEfectivo);
        rbEfectivo.setText("Efectivo");
        rbEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEfectivoActionPerformed(evt);
            }
        });

        bgFormaDePago.add(rbCuentaBancaria);
        rbCuentaBancaria.setText("Cuenta bancaria");
        rbCuentaBancaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCuentaBancariaActionPerformed(evt);
            }
        });

        jLabel12.setText("Tarifa:");

        txNuevoEmail.setText("jTextField2");

        cbNuevoTarifa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbNuevoTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNuevoTarifaActionPerformed(evt);
            }
        });

        jLabel9.setText("Cuenta bancaria:");

        txNuevoCuentaBancaria.setText("jTextField8");
        txNuevoCuentaBancaria.setEnabled(false);

        jLabel11.setText("Fecha de nacimiento:");

        jLabel14.setText("Email:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNuevoEmail)
                    .addComponent(txNuevoNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbNuevoTarifa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txNuevoCuentaBancaria)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rbEfectivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(rbCuentaBancaria))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(txNuevoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNuevoNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbNuevoTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rbEfectivo)
                    .addComponent(rbCuentaBancaria))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNuevoCuentaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jLabel15.setText("Cógido postal:");

        txNuevoCodigoPostal.setText("jTextField1");
        txNuevoCodigoPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNuevoCodigoPostalActionPerformed(evt);
            }
        });

        jLabel16.setText("Localidad:");

        txNuevoLocalidad.setText("jTextField1");

        jLabel17.setText("Provincia:");

        txNuevoProvincia.setText("jTextField1");

        botonLimpiar.setText("Limpiar formulario");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        bGuardarCliente.setText("Guardar");
        bGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15))
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txNuevoCodigoPostal)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txNumeroDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txNuevoPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txNuevoDireccion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(99, 99, 99)
                        .addComponent(txNuevoMovil))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txNuevoDni, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addComponent(txNuevoApellidos)
                            .addComponent(txNuevoNombre)
                            .addComponent(txNuevoTelefono)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txNuevoLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txNuevoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(botonLimpiar)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txNuevoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txNuevoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txNuevoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(1, 1, 1)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txNuevoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txNuevoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txNumeroDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txNuevoPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txNuevoCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txNuevoLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txNuevoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        Ventana_clientes_busqueda.addTab("Nuevo cliente", jPanel1);

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        botonEditarCliente.setText("Editar ");
        botonEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarClienteActionPerformed(evt);
            }
        });

        botonBorrarCliente.setText("Borrar ");
        botonBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarClienteActionPerformed(evt);
            }
        });

        botonDetalles.setText("Detalles");
        botonDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetallesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(botonEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(botonBorrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(botonDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonBorrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(botonDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Ventana_clientes_busqueda.addTab("Lista clientes", jPanel2);

        jLabel19.setText("Buscar:");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(tableBusquedas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel19)
                        .addGap(77, 77, 77)
                        .addComponent(txBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(botonBuscar))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        Ventana_clientes_busqueda.addTab("Búsquedas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ventana_clientes_busqueda)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Ventana_clientes_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCuentaBancariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCuentaBancariaActionPerformed
        txNuevoCuentaBancaria.setEnabled(true);
    }//GEN-LAST:event_rbCuentaBancariaActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        VentanaUtils.limpiarFormulario(jPanel1);
    }//GEN-LAST:event_botonLimpiarActionPerformed


    private void txNuevoCodigoPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNuevoCodigoPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNuevoCodigoPostalActionPerformed

    private void txNuevoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNuevoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNuevoTelefonoActionPerformed

    private void bGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarClienteActionPerformed

        if (!Patrones.validarCodigoPostal(txNuevoCodigoPostal.getText())) {
            JOptionPane.showMessageDialog(this, "El código postal introducido es incorrecto");
            return;
        }

        if (!Patrones.validarDni(txNuevoDni.getText())) {
            JOptionPane.showMessageDialog(this, "El DNI introducido es incorrecto");
            return;
        }

        if (!Patrones.validarEmail(txNuevoEmail.getText())) {
            JOptionPane.showMessageDialog(this, "El email introducido es incorrecto");
            return;
        }

        if (!Patrones.validarTelefonoMovil(txNuevoMovil.getText())) {
            JOptionPane.showMessageDialog(this, "El teléfono móvil introducido es incorrecto");
            return;
        }

        String formaPago = this.formaDePago();

        try {
            Clientes cliente = new Clientes(txNuevoNombre.getText(), txNuevoApellidos.getText(),
                    txNuevoDni.getText(), txNuevoTelefono.getText(),
                    txNuevoMovil.getText(), txNuevoDireccion.getText(),
                    txNuevoPiso.getText(), txNumeroDomicilio.getText(),
                    Integer.parseInt(txNuevoCodigoPostal.getText()), txNuevoLocalidad.getText(),
                    txNuevoProvincia.getText(), txNuevoNacimiento.getDate(),
                    txNuevoCuentaBancaria.getText(), txNuevoEmail.getText(),
                    Gestora.fechaActual(), ((Tarifas) cbNuevoTarifa.getSelectedItem()).getIdTarifa(), formaPago,
                    Login.getEmpleadoAutenticado().getIdEmpleado());

            GestoraClientes.guardarCliente(cliente);
            tablaClientes.setModel(new ModeloTablaClientes(GestoraClientes.recuperarClientes()));
            JOptionPane.showMessageDialog(this, "Se ha introducido el cliente correctamente.");
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "No se ha podido introducir el cliente correctamente.");
        } catch (HeadlessException headlessException) {
            JOptionPane.showMessageDialog(this, "No se ha podido introducir el cliente correctamente.");
        }
    }//GEN-LAST:event_bGuardarClienteActionPerformed

    private void botonEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarClienteActionPerformed

        int row = tablaClientes.getSelectedRow();
        if (row >= 0) {
            new VentanaClientesEdicion((Frame) this.getParent(), true, (int) tablaClientes.getValueAt(row, 0)).setVisible(true);
        }
    }//GEN-LAST:event_botonEditarClienteActionPerformed

    private void botonBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarClienteActionPerformed
        int row = tablaClientes.getSelectedRow();
        if (row >= 0) {
            try {
                int resultado = JOptionPane.showConfirmDialog(this, "¿Esta seguro borrar ese cliente?", null, JOptionPane.YES_OPTION);

                if (resultado == JOptionPane.YES_OPTION) {
                    GestoraClientes.borrarCliente(GestoraClientes.getClientePorId((int) tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 0)));
                } else {
                    JOptionPane.showMessageDialog(this, "El cliente no se ha borrado.");
                }

                tablaClientes.setModel(new ModeloTablaClientes(GestoraClientes.recuperarClientes()));
                JOptionPane.showMessageDialog(this, "Cliente borrado.");
            } catch (HeadlessException headlessException) {
                JOptionPane.showMessageDialog(this, "No se ha podido borrar el cliente correctamente.");
            }
        }
    }//GEN-LAST:event_botonBorrarClienteActionPerformed

    private void cbNuevoTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNuevoTarifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNuevoTarifaActionPerformed

    private void rbEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEfectivoActionPerformed
        txNuevoCuentaBancaria.setEnabled(false);
    }//GEN-LAST:event_rbEfectivoActionPerformed

    private void botonDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetallesActionPerformed
        int row = tablaClientes.getSelectedRow();
        if (row >= 0) {
            new VentanaClientesDetalle((Frame) this.getParent(), true, (int) tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 0)).setVisible(true);
        }
    }//GEN-LAST:event_botonDetallesActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void txNuevoTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNuevoTelefonoKeyTyped
        comprobarNumerico(txNuevoTelefono, evt);
    }//GEN-LAST:event_txNuevoTelefonoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Ventana_clientes_busqueda;
    private javax.swing.JToggleButton bGuardarCliente;
    private javax.swing.ButtonGroup bgFormaDePago;
    private javax.swing.JButton botonBorrarCliente;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonDetalles;
    private javax.swing.JButton botonEditarCliente;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JComboBox cbNuevoTarifa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbCuentaBancaria;
    private javax.swing.JRadioButton rbEfectivo;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tableBusquedas;
    private javax.swing.JTextField txBusqueda;
    private javax.swing.JTextField txNuevoApellidos;
    private javax.swing.JTextField txNuevoCodigoPostal;
    private javax.swing.JTextField txNuevoCuentaBancaria;
    private javax.swing.JTextField txNuevoDireccion;
    private javax.swing.JTextField txNuevoDni;
    private javax.swing.JTextField txNuevoEmail;
    private javax.swing.JTextField txNuevoLocalidad;
    private javax.swing.JTextField txNuevoMovil;
    private com.toedter.calendar.JDateChooser txNuevoNacimiento;
    private javax.swing.JTextField txNuevoNombre;
    private javax.swing.JTextField txNuevoPiso;
    private javax.swing.JTextField txNuevoProvincia;
    private javax.swing.JTextField txNuevoTelefono;
    private javax.swing.JTextField txNumeroDomicilio;
    // End of variables declaration//GEN-END:variables

    public String formaDePago() {

        if (rbCuentaBancaria.isSelected() == true) {
            return "Cuenta bancaria";
        }
        return "Efectivo";
    }

    public void getTarifas() {
        List<Tarifas> lista = GestoraTarifas.recuperarTarifas();
        cbNuevoTarifa.setModel(new DefaultComboBoxModel(lista.toArray(new Tarifas[lista.size()])));
        cbNuevoTarifa.addItem("");
    }

    private void buscar() {

        String buscar = txBusqueda.getText();
        int buscarN = 0;
        if (Patrones.isNumeric(buscar)) {
            buscarN = Integer.parseInt(buscar);
        }
        if (!buscar.isEmpty()) {

            Session s = Gestora.getInstance().openSession();
            Query q = s.createQuery("from Clientes t where t.nombreCliente = :n or "
                    + "t.apellidosCliente = :min or "
                    + "t.dniCliente = :d or "
                    + "t.telefonoCliente = :tc or "
                    + "t.telefonomovilCliente = :tm or "
                    + "t.direcciondomicilioCliente = :dir or "
                    + "t.pisodomicilioCliente = :piso or "
                    + "t.numerodomicilioCliente = :num or "
                    + "t.codigopostalCliente = :cod or "
                    + "t.localidadCliente = :loc or "
                    + "t.provinciaCliente = :prov or "
                    + "t.cuentabancariaCliente = :cuen or "
                    + "t.emailCliente = :email or "
                    + "t.formapagoCliente = :forma");
            q.setParameter("n", buscar);
            q.setParameter("min", buscar);
            q.setParameter("d", buscar);
            q.setParameter("tc", buscar);
            q.setParameter("tm", buscar);
            q.setParameter("dir", buscar);
            q.setParameter("piso", buscar);
            q.setParameter("num", buscar);
            q.setParameter("cod", buscarN);
            q.setParameter("loc", buscar);
            q.setParameter("prov", buscar);
            q.setParameter("cuen", buscar);
            q.setParameter("email", buscar);
            q.setParameter("forma", buscar);
            tableBusquedas.setModel(new ModeloTablaClientes(q.list()));
        }
    }

    public void comprobarNumerico(JTextField campo, java.awt.event.KeyEvent evt) {

        char car = evt.getKeyChar();
        if (((car < '0' || car > '9') && car != '.') || campo.getText().contains(".") && car == '.') {
            evt.consume();
        }

    }
}
