package Primero;

// Generated 13-abr-2015 21:47:45 by Hibernate Tools 3.4.0.CR1

/**
 * Actividadestarifas generated by hbm2java
 */
public class Actividadestarifas implements java.io.Serializable {

	private ActividadestarifasId id;

	public Actividadestarifas() {
	}

	public Actividadestarifas(ActividadestarifasId id) {
		this.id = id;
	}

	public ActividadestarifasId getId() {
		return this.id;
	}

	public void setId(ActividadestarifasId id) {
		this.id = id;
	}

}
