package Primero;

// Generated 13-abr-2015 21:47:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private Integer idCliente;
	private String nombreCliente;
	private String apellidosCliente;
	private String dniCliente;
	private Integer viviendaCliente;
	private String cuentabancariaCliente;
	private Date fechanacimientoCliente;
	private String emailCliente;
	private String telefonoCliente;
	private String movilCliente;
	private Date fechaaltaCliente;
	private Integer idTarifaCliente;
	private String formapagoCliente;
	private String tipoViaDomicilioCliente;
	private String direccionDomicilioCliente;
	private String pisoDomicilio;
	private String numeroDomicilio;
	private Integer codigoPostalCliente;
	private String localidadCliente;
	private String provinciaCliente;

	public Clientes() {
	}

	public Clientes(String dniCliente, String cuentabancariaCliente,
			Date fechanacimientoCliente, String formapagoCliente) {
		this.dniCliente = dniCliente;
		this.cuentabancariaCliente = cuentabancariaCliente;
		this.fechanacimientoCliente = fechanacimientoCliente;
		this.formapagoCliente = formapagoCliente;
	}

	public Clientes(String nombreCliente, String apellidosCliente,
			String dniCliente, Integer viviendaCliente,
			String cuentabancariaCliente, Date fechanacimientoCliente,
			String emailCliente, String telefonoCliente, String movilCliente,
			Date fechaaltaCliente, Integer idTarifaCliente,
			String formapagoCliente, String tipoViaDomicilioCliente,
			String direccionDomicilioCliente, String pisoDomicilio,
			String numeroDomicilio, Integer codigoPostalCliente,
			String localidadCliente, String provinciaCliente) {
		this.nombreCliente = nombreCliente;
		this.apellidosCliente = apellidosCliente;
		this.dniCliente = dniCliente;
		this.viviendaCliente = viviendaCliente;
		this.cuentabancariaCliente = cuentabancariaCliente;
		this.fechanacimientoCliente = fechanacimientoCliente;
		this.emailCliente = emailCliente;
		this.telefonoCliente = telefonoCliente;
		this.movilCliente = movilCliente;
		this.fechaaltaCliente = fechaaltaCliente;
		this.idTarifaCliente = idTarifaCliente;
		this.formapagoCliente = formapagoCliente;
		this.tipoViaDomicilioCliente = tipoViaDomicilioCliente;
		this.direccionDomicilioCliente = direccionDomicilioCliente;
		this.pisoDomicilio = pisoDomicilio;
		this.numeroDomicilio = numeroDomicilio;
		this.codigoPostalCliente = codigoPostalCliente;
		this.localidadCliente = localidadCliente;
		this.provinciaCliente = provinciaCliente;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public String getNombreCliente() {
		return this.nombreCliente;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombreCliente = nombreCliente;
	}

	public String getApellidosCliente() {
		return this.apellidosCliente;
	}

	public void setApellidosCliente(String apellidosCliente) {
		this.apellidosCliente = apellidosCliente;
	}

	public String getDniCliente() {
		return this.dniCliente;
	}

	public void setDniCliente(String dniCliente) {
		this.dniCliente = dniCliente;
	}

	public Integer getViviendaCliente() {
		return this.viviendaCliente;
	}

	public void setViviendaCliente(Integer viviendaCliente) {
		this.viviendaCliente = viviendaCliente;
	}

	public String getCuentabancariaCliente() {
		return this.cuentabancariaCliente;
	}

	public void setCuentabancariaCliente(String cuentabancariaCliente) {
		this.cuentabancariaCliente = cuentabancariaCliente;
	}

	public Date getFechanacimientoCliente() {
		return this.fechanacimientoCliente;
	}

	public void setFechanacimientoCliente(Date fechanacimientoCliente) {
		this.fechanacimientoCliente = fechanacimientoCliente;
	}

	public String getEmailCliente() {
		return this.emailCliente;
	}

	public void setEmailCliente(String emailCliente) {
		this.emailCliente = emailCliente;
	}

	public String getTelefonoCliente() {
		return this.telefonoCliente;
	}

	public void setTelefonoCliente(String telefonoCliente) {
		this.telefonoCliente = telefonoCliente;
	}

	public String getMovilCliente() {
		return this.movilCliente;
	}

	public void setMovilCliente(String movilCliente) {
		this.movilCliente = movilCliente;
	}

	public Date getFechaaltaCliente() {
		return this.fechaaltaCliente;
	}

	public void setFechaaltaCliente(Date fechaaltaCliente) {
		this.fechaaltaCliente = fechaaltaCliente;
	}

	public Integer getIdTarifaCliente() {
		return this.idTarifaCliente;
	}

	public void setIdTarifaCliente(Integer idTarifaCliente) {
		this.idTarifaCliente = idTarifaCliente;
	}

	public String getFormapagoCliente() {
		return this.formapagoCliente;
	}

	public void setFormapagoCliente(String formapagoCliente) {
		this.formapagoCliente = formapagoCliente;
	}

	public String getTipoViaDomicilioCliente() {
		return this.tipoViaDomicilioCliente;
	}

	public void setTipoViaDomicilioCliente(String tipoViaDomicilioCliente) {
		this.tipoViaDomicilioCliente = tipoViaDomicilioCliente;
	}

	public String getDireccionDomicilioCliente() {
		return this.direccionDomicilioCliente;
	}

	public void setDireccionDomicilioCliente(String direccionDomicilioCliente) {
		this.direccionDomicilioCliente = direccionDomicilioCliente;
	}

	public String getPisoDomicilio() {
		return this.pisoDomicilio;
	}

	public void setPisoDomicilio(String pisoDomicilio) {
		this.pisoDomicilio = pisoDomicilio;
	}

	public String getNumeroDomicilio() {
		return this.numeroDomicilio;
	}

	public void setNumeroDomicilio(String numeroDomicilio) {
		this.numeroDomicilio = numeroDomicilio;
	}

	public Integer getCodigoPostalCliente() {
		return this.codigoPostalCliente;
	}

	public void setCodigoPostalCliente(Integer codigoPostalCliente) {
		this.codigoPostalCliente = codigoPostalCliente;
	}

	public String getLocalidadCliente() {
		return this.localidadCliente;
	}

	public void setLocalidadCliente(String localidadCliente) {
		this.localidadCliente = localidadCliente;
	}

	public String getProvinciaCliente() {
		return this.provinciaCliente;
	}

	public void setProvinciaCliente(String provinciaCliente) {
		this.provinciaCliente = provinciaCliente;
	}

}
