package Primero;

// Generated 13-abr-2015 21:47:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * HorariosActividades generated by hbm2java
 */
public class HorariosActividades implements java.io.Serializable {

	private int idHorario;
	private Integer idactividadHorario;
	private String diaHorario;
	private Date horainicioHorario;
	private Date horafinHorario;

	public HorariosActividades() {
	}

	public HorariosActividades(int idHorario) {
		this.idHorario = idHorario;
	}

	public HorariosActividades(int idHorario, Integer idactividadHorario,
			String diaHorario, Date horainicioHorario, Date horafinHorario) {
		this.idHorario = idHorario;
		this.idactividadHorario = idactividadHorario;
		this.diaHorario = diaHorario;
		this.horainicioHorario = horainicioHorario;
		this.horafinHorario = horafinHorario;
	}

	public int getIdHorario() {
		return this.idHorario;
	}

	public void setIdHorario(int idHorario) {
		this.idHorario = idHorario;
	}

	public Integer getIdactividadHorario() {
		return this.idactividadHorario;
	}

	public void setIdactividadHorario(Integer idactividadHorario) {
		this.idactividadHorario = idactividadHorario;
	}

	public String getDiaHorario() {
		return this.diaHorario;
	}

	public void setDiaHorario(String diaHorario) {
		this.diaHorario = diaHorario;
	}

	public Date getHorainicioHorario() {
		return this.horainicioHorario;
	}

	public void setHorainicioHorario(Date horainicioHorario) {
		this.horainicioHorario = horainicioHorario;
	}

	public Date getHorafinHorario() {
		return this.horafinHorario;
	}

	public void setHorafinHorario(Date horafinHorario) {
		this.horafinHorario = horafinHorario;
	}

}
