package Primero;

// Generated 13-abr-2015 21:47:45 by Hibernate Tools 3.4.0.CR1

/**
 * Provincias generated by hbm2java
 */
public class Provincias implements java.io.Serializable {

	private Integer idProvincia;
	private int codigoProvincia;
	private String nombreProvincia;

	public Provincias() {
	}

	public Provincias(int codigoProvincia, String nombreProvincia) {
		this.codigoProvincia = codigoProvincia;
		this.nombreProvincia = nombreProvincia;
	}

	public Integer getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(Integer idProvincia) {
		this.idProvincia = idProvincia;
	}

	public int getCodigoProvincia() {
		return this.codigoProvincia;
	}

	public void setCodigoProvincia(int codigoProvincia) {
		this.codigoProvincia = codigoProvincia;
	}

	public String getNombreProvincia() {
		return this.nombreProvincia;
	}

	public void setNombreProvincia(String nombreProvincia) {
		this.nombreProvincia = nombreProvincia;
	}

}
